name: flutterprojeto_3
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  http: 1.2.2
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/img/ball.png

  fonts:
    - family: ConcertOne
      fonts:
        - asset: lib/fonts/ConcertOne-Regular.ttf